@WebApiWithMcp_HostAddress = https://localhost:7055

GET {{WebApiWithMcp_HostAddress}}/weatherforecast/?zipCode=53150
Accept: application/json

###

GET {{WebApiWithMcp_HostAddress}}/mcp
Accept: application/json

###
